// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThreadLab.Database;

#nullable disable

namespace ThreadLab.Migrations
{
    [DbContext(typeof(ThreadDbContext))]
    partial class ThreadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThreadLab.Database.ThreadIteration", b =>
                {
                    b.Property<int>("ThreadIterationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadIterationId"));

                    b.Property<DateTime?>("DateTimeFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<long>("EndNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBackground")
                        .HasColumnType("bit");

                    b.Property<int>("ManagedThreadId")
                        .HasColumnType("int");

                    b.Property<long>("StartNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ThreadJobId")
                        .HasColumnType("int");

                    b.HasKey("ThreadIterationId");

                    b.HasIndex("ThreadJobId");

                    b.ToTable("ThreadIterations");
                });

            modelBuilder.Entity("ThreadLab.Database.ThreadJob", b =>
                {
                    b.Property<int>("ThreadJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadJobId"));

                    b.Property<DateTime?>("DateTimeFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBackground")
                        .HasColumnType("bit");

                    b.Property<int>("ManagedThreadId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStepsPerThread")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfThreads")
                        .HasColumnType("int");

                    b.HasKey("ThreadJobId");

                    b.ToTable("ThreadJobs");
                });

            modelBuilder.Entity("ThreadLab.Database.ThreadIteration", b =>
                {
                    b.HasOne("ThreadLab.Database.ThreadJob", null)
                        .WithMany("ThreadIterations")
                        .HasForeignKey("ThreadJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThreadLab.Database.ThreadJob", b =>
                {
                    b.Navigation("ThreadIterations");
                });
#pragma warning restore 612, 618
        }
    }
}
